/**
 * Deterministic generation of the published TypeScript module from
 * collected class names. Same input always renders byte-for-byte
 * identical output (no timestamps), so diffs reflect real changes only.
 */
import { classSelector, stableSelector } from "./classnames.ts";

function renderRecord(entries: readonly (readonly [string, string])[]): string {
	if (entries.length === 0) return "{}";
	const body = entries
		.map(([name, value]) => `  ${JSON.stringify(name)}: ${value},`)
		.join("\n");
	return `{\n${body}\n}`;
}

/** Render the full `src/index.ts` source for the collected class names. */
export function renderModule(
	collected: Record<string, readonly string[]>,
	pattern?: RegExp,
): string {
	const names = Object.keys(collected).sort();
	const classNames = names.map(
		(name) =>
			[
				name,
				`[${collected[name]?.map((token) => JSON.stringify(token)).join(", ")}]`,
			] as const,
	);
	const selectors = names.map(
		(name) => [name, JSON.stringify(classSelector(collected[name]!))] as const,
	);
	const stableSelectors = names.map(
		(name) =>
			[
				name,
				JSON.stringify(stableSelector(collected[name]!, pattern)),
			] as const,
	);

	return [
		"// auto-generated by scripts/extract.ts — DO NOT EDIT",
		"",
		"/** Element name → observed class name tokens. */",
		`export const classNames = ${renderRecord(classNames)} as const;`,
		"",
		"/** Element name → exact CSS selector (all observed tokens). */",
		`export const selectors = ${renderRecord(selectors)} as const;`,
		"",
		"/** Element name → hash-tolerant CSS selector (survives hash changes). */",
		`export const stableSelectors = ${renderRecord(stableSelectors)} as const;`,
		"",
		"export type ElementName = keyof typeof classNames;",
		"",
	].join("\n");
}
