// auto-generated by scripts/extract.ts — DO NOT EDIT

/** Element name → observed class name tokens. */
export const classNames = {
  "breadcrumbItem": ["sc-1mr8gis-0", "kZYrPk"],
  "breadcrumbList": ["sc-1mr8gis-4", "bolqeU"],
  "chapterHeader": ["sc-aXZVg", "gPvMWS"],
  "chapterList": ["sc-1qnak7i-0", "eYfwpG"],
  "chapterListItem": ["sc-10digve-0", "kjrMxR"],
  "courseHeader": ["sc-1g1n70x-0", "fHOtAw"],
  "exerciseSectionHeader": ["sc-1qf3z6b-2", "gSFcmh"],
  "homeCourseCount": ["sc-aXZVg", "gXtGFW"],
  "homeCourseElement": ["sc-aXZVg", "fYHoYN"],
  "homeCourseList": ["sc-aXZVg", "GIIGO"],
  "movieSectionHeader": ["sc-1qf3z6b-2", "gSFcmh"],
  "movieSectionReference": ["sc-aXZVg", "sc-82no5l-0", "gKkuPT", "iszKWf"],
  "movieSectionVideo": ["sc-aXZVg", "cswXEj"],
  "nextChapterButton": ["sc-aXZVg", "bhKrcp", "sc-13j7nb-0", "jTSQNP"],
  "prevChapterButton": ["sc-aXZVg", "bhKrcp", "sc-13j7nb-0", "jTSQNP"],
  "registeredCourseIndicator": ["sc-11in5kn-0", "jTMKEj"],
  "sectionList": ["sc-aXZVg", "sc-gEvEer", "sc-1at0r9g-0", "dKubqp", "fteAEG", "hFtzCB"],
  "sectionListItem": ["sc-aXZVg", "sc-gEvEer", "hYNtMZ", "fteAEG", "sc-1otp79h-0", "sc-15ar6v9-0", "dPmAoN", "kNgKxU"],
  "sectionListItemCurrentIndicator": ["sc-aXZVg", "sc-gEvEer", "sc-1wngno8-10", "sc-15ar6v9-1", "dKubqp", "fteAEG", "ghmxKl"],
} as const;

/** Element name → exact CSS selector (all observed tokens). */
export const selectors = {
  "breadcrumbItem": ".sc-1mr8gis-0.kZYrPk",
  "breadcrumbList": ".sc-1mr8gis-4.bolqeU",
  "chapterHeader": ".sc-aXZVg.gPvMWS",
  "chapterList": ".sc-1qnak7i-0.eYfwpG",
  "chapterListItem": ".sc-10digve-0.kjrMxR",
  "courseHeader": ".sc-1g1n70x-0.fHOtAw",
  "exerciseSectionHeader": ".sc-1qf3z6b-2.gSFcmh",
  "homeCourseCount": ".sc-aXZVg.gXtGFW",
  "homeCourseElement": ".sc-aXZVg.fYHoYN",
  "homeCourseList": ".sc-aXZVg.GIIGO",
  "movieSectionHeader": ".sc-1qf3z6b-2.gSFcmh",
  "movieSectionReference": ".sc-aXZVg.sc-82no5l-0.gKkuPT.iszKWf",
  "movieSectionVideo": ".sc-aXZVg.cswXEj",
  "nextChapterButton": ".sc-aXZVg.bhKrcp.sc-13j7nb-0.jTSQNP",
  "prevChapterButton": ".sc-aXZVg.bhKrcp.sc-13j7nb-0.jTSQNP",
  "registeredCourseIndicator": ".sc-11in5kn-0.jTMKEj",
  "sectionList": ".sc-aXZVg.sc-gEvEer.sc-1at0r9g-0.dKubqp.fteAEG.hFtzCB",
  "sectionListItem": ".sc-aXZVg.sc-gEvEer.hYNtMZ.fteAEG.sc-1otp79h-0.sc-15ar6v9-0.dPmAoN.kNgKxU",
  "sectionListItemCurrentIndicator": ".sc-aXZVg.sc-gEvEer.sc-1wngno8-10.sc-15ar6v9-1.dKubqp.fteAEG.ghmxKl",
} as const;

/** Element name → hash-tolerant CSS selector (survives hash changes). */
export const stableSelectors = {
  "breadcrumbItem": ".sc-1mr8gis-0",
  "breadcrumbList": ".sc-1mr8gis-4",
  "chapterHeader": ".sc-aXZVg",
  "chapterList": ".sc-1qnak7i-0",
  "chapterListItem": ".sc-10digve-0",
  "courseHeader": ".sc-1g1n70x-0",
  "exerciseSectionHeader": ".sc-1qf3z6b-2",
  "homeCourseCount": ".sc-aXZVg",
  "homeCourseElement": ".sc-aXZVg",
  "homeCourseList": ".sc-aXZVg",
  "movieSectionHeader": ".sc-1qf3z6b-2",
  "movieSectionReference": ".sc-aXZVg.sc-82no5l-0",
  "movieSectionVideo": ".sc-aXZVg",
  "nextChapterButton": ".sc-aXZVg.sc-13j7nb-0",
  "prevChapterButton": ".sc-aXZVg.sc-13j7nb-0",
  "registeredCourseIndicator": ".sc-11in5kn-0",
  "sectionList": ".sc-aXZVg.sc-gEvEer.sc-1at0r9g-0",
  "sectionListItem": ".sc-aXZVg.sc-gEvEer.sc-1otp79h-0.sc-15ar6v9-0",
  "sectionListItemCurrentIndicator": ".sc-aXZVg.sc-gEvEer.sc-1wngno8-10.sc-15ar6v9-1",
} as const;

export type ElementName = keyof typeof classNames;
